version: '3'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    cpus: 1
    mem_limit: 2048m
    mem_reservation: 2048m
    cap_add:
      - SYS_NICE
      - NET_ADMIN 
      - IPC_LOCK
    ports:
      - 18123:8123
      - 19000:9000
      - 19009:9009
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d/ddl.sql
        target: /docker-entrypoint-initdb.d/ddl.sql
      - type: bind
        source: ./clickhouse.config.d/z_log_disable.xml
        target: /etc/clickhouse-server/config.d/z_log_disable.xml
      - type: bind
        source: ./clickhouse.config.d/asynchronous_metrics_update_period_s.xml
        target: /etc/clickhouse-server/config.d/asynchronous_metrics_update_period_s.xml
      - clickhouse-volume:/var/lib/clickhouse/
      - clickhouse-volume:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  adventureworks:
    image: postgres
    networks:
      - superset-network
    environment:
      - POSTGRES_DB=Adventureworks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./docker-entrypoint-initdb.d/adventureworks.sh
        target: /docker-entrypoint-initdb.d/adventureworks.sh
      - type: bind
        source: adventureworks
        target: /adventureworks
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Adventureworks"]
      interval: 10s
      timeout: 5s
      retries: 30
    
  superset:
    image: apache/superset
    networks:
      - superset-network
    depends_on:
      adventureworks:
        condition: service_healthy
    init: true
    links:
      - adventureworks:adventureworks
    volumes:
      - ./superset_home:/app/superset_home
      - type: bind
        source: ./docker-entrypoint-initdb.d/superset.sh
        target: /docker-entrypoint-initdb.d/superset.sh
    entrypoint: ["/docker-entrypoint-initdb.d/superset.sh"]
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_home/superset_config.py
    ports:
      - '18080:8088'

volumes:
  clickhouse-volume:
  postgres-data:

networks:
  superset-network:
    driver: bridge